"""initial_schema

Revision ID: 4f8f3d7e04e8
Revises: 
Create Date: 2026-05-27 13:55:17.465548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8f3d7e04e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writes')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('checkpoint', sa.BLOB(), nullable=True),
    sa.Column('metadata', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    op.create_table('writes',
    sa.Column('thread_id', sa.TEXT(), nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), nullable=False),
    sa.Column('task_id', sa.TEXT(), nullable=False),
    sa.Column('idx', sa.INTEGER(), nullable=False),
    sa.Column('channel', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('value', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')
    )
    # ### end Alembic commands ###
